package models

func GetDefaultProducts() []Product {
	return []Product{
		// FRUTAS
		{Name: "Arándanos", Stock: 0, Type: Fruit, Measurement: Kilos},
		{Name: "Banana", Stock: 0, Type: Fruit, Measurement: Kilos},
		{Name: "Cereza", Stock: 0, Type: Fruit, Measurement: Kilos},
		{Name: "Ciruela", Stock: 0, Type: Fruit, Measurement: Kilos},
		{Name: "Damasco", Stock: 0, Type: Fruit, Measurement: Kilos},
		{Name: "Durazno", Stock: 0, Type: Fruit, Measurement: Kilos},
		{Name: "Frutilla", Stock: 0, Type: Fruit, Measurement: Kilos},
		{Name: "Higo", Stock: 0, Type: Fruit, Measurement: Kilos},
		{Name: "Kiwi", Stock: 0, Type: Fruit, Measurement: Kilos},
		{Name: "Limón", Stock: 0, Type: Fruit, Measurement: Kilos},
		{Name: "Mandarina", Stock: 0, Type: Fruit, Measurement: Kilos},
		{Name: "Manzana Roja", Stock: 0, Type: Fruit, Measurement: Kilos},
		{Name: "Manzana Verde", Stock: 0, Type: Fruit, Measurement: Kilos},
		{Name: "Melón", Stock: 0, Type: Fruit, Measurement: Unidades},
		{Name: "Naranja", Stock: 0, Type: Fruit, Measurement: Kilos},
		{Name: "Palta", Stock: 0, Type: Fruit, Measurement: Unidades},
		{Name: "Pera", Stock: 0, Type: Fruit, Measurement: Kilos},
		{Name: "Pomelo", Stock: 0, Type: Fruit, Measurement: Kilos},
		{Name: "Sandía", Stock: 0, Type: Fruit, Measurement: Unidades},
		{Name: "Uva", Stock: 0, Type: Fruit, Measurement: Kilos},

		// HORTALIZAS
		{Name: "Acelga", Stock: 0, Type: Ortaliza, Measurement: Unidades},
		{Name: "Albahaca", Stock: 0, Type: Ortaliza, Measurement: Unidades},
		{Name: "Apio", Stock: 0, Type: Ortaliza, Measurement: Unidades},
		{Name: "Brócoli", Stock: 0, Type: Ortaliza, Measurement: Kilos},
		{Name: "Cilantro", Stock: 0, Type: Ortaliza, Measurement: Unidades},
		{Name: "Coliflor", Stock: 0, Type: Ortaliza, Measurement: Unidades},
		{Name: "Espinaca", Stock: 0, Type: Ortaliza, Measurement: Unidades},
		{Name: "Lechuga Capuchina", Stock: 0, Type: Ortaliza, Measurement: Kilos},
		{Name: "Lechuga Criolla", Stock: 0, Type: Ortaliza, Measurement: Kilos},
		{Name: "Lechuga Mantecosa", Stock: 0, Type: Ortaliza, Measurement: Kilos},
		{Name: "Perejil", Stock: 0, Type: Ortaliza, Measurement: Unidades},
		{Name: "Radicheta", Stock: 0, Type: Ortaliza, Measurement: Unidades},
		{Name: "Repollo Blanco", Stock: 0, Type: Ortaliza, Measurement: Unidades},
		{Name: "Repollo Colorado", Stock: 0, Type: Ortaliza, Measurement: Unidades},
		{Name: "Rúcula", Stock: 0, Type: Ortaliza, Measurement: Unidades},

		// VEGETALES
		{Name: "Ajo", Stock: 0, Type: Vegetable, Measurement: Unidades},
		{Name: "Batata", Stock: 0, Type: Vegetable, Measurement: Kilos},
		{Name: "Berenjena", Stock: 0, Type: Vegetable, Measurement: Kilos},
		{Name: "Cebolla", Stock: 0, Type: Vegetable, Measurement: Kilos},
		{Name: "Cebolla Morada", Stock: 0, Type: Vegetable, Measurement: Kilos},
		{Name: "Chaucha", Stock: 0, Type: Vegetable, Measurement: Kilos},
		{Name: "Choclo", Stock: 0, Type: Vegetable, Measurement: Unidades},
		{Name: "Espárragos", Stock: 0, Type: Vegetable, Measurement: Unidades},
		{Name: "Hinojo", Stock: 0, Type: Vegetable, Measurement: Kilos},
		{Name: "Morrón Rojo", Stock: 0, Type: Vegetable, Measurement: Kilos},
		{Name: "Morrón Verde", Stock: 0, Type: Vegetable, Measurement: Kilos},
		{Name: "Papa Blanca", Stock: 0, Type: Vegetable, Measurement: Kilos},
		{Name: "Papa Negra", Stock: 0, Type: Vegetable, Measurement: Kilos},
		{Name: "Pepino", Stock: 0, Type: Vegetable, Measurement: Unidades},
		{Name: "Puerro", Stock: 0, Type: Vegetable, Measurement: Unidades},
		{Name: "Remolacha", Stock: 0, Type: Vegetable, Measurement: Kilos},
		{Name: "Tomate Cherry", Stock: 0, Type: Vegetable, Measurement: Kilos},
		{Name: "Tomate Perita", Stock: 0, Type: Vegetable, Measurement: Kilos},
		{Name: "Tomate Redondo", Stock: 0, Type: Vegetable, Measurement: Kilos},
		{Name: "Verdeo", Stock: 0, Type: Vegetable, Measurement: Unidades},
		{Name: "Zanahoria", Stock: 0, Type: Vegetable, Measurement: Kilos},
		{Name: "Zapallito", Stock: 0, Type: Vegetable, Measurement: Kilos},
		{Name: "Zapallo Anco", Stock: 0, Type: Vegetable, Measurement: Kilos},
		{Name: "Zapallo Cabutia", Stock: 0, Type: Vegetable, Measurement: Kilos},
		{Name: "Zucchini", Stock: 0, Type: Vegetable, Measurement: Kilos},

		// OTROS
		{Name: "Carbón", Stock: 0, Type: Other, Measurement: Unidades},
		{Name: "Hongos", Stock: 0, Type: Other, Measurement: Kilos},
		{Name: "Huevos", Stock: 0, Type: Other, Measurement: Unidades},
		{Name: "Miel", Stock: 0, Type: Other, Measurement: Unidades},
	}
}
